eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: product
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Shell?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  rabbitmq:
    addresses: 192.168.99.100
    port: 5672
    username: guest
    password: guest
